import Link from 'next/link'

export const metadata = {
  title: 'Privacy Policy — BikerOrNot',
}

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-zinc-950 text-white">
      {/* Header */}
      <header className="border-b border-zinc-800 bg-zinc-900">
        <div className="max-w-3xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link href="/" className="text-lg font-black tracking-tight">
            Biker<span className="text-orange-500">Or</span>Not
          </Link>
          <Link href="/login" className="text-sm text-zinc-400 hover:text-white transition-colors">
            Sign in
          </Link>
        </div>
      </header>

      <div className="max-w-3xl mx-auto px-6 py-12">
        <h1 className="text-3xl font-black text-white mb-2">Privacy Policy</h1>
        <p className="text-zinc-500 text-sm mb-6">Effective Date: February 24, 2026</p>

        {/* Intro */}
        <div className="bg-zinc-900 border border-zinc-800 rounded-xl p-5 mb-10">
          <p className="text-zinc-300 leading-relaxed">
            BikerOrNot.com (&ldquo;BikerOrNot,&rdquo; &ldquo;we,&rdquo; &ldquo;our,&rdquo; or &ldquo;us&rdquo;) is committed to protecting
            your privacy. This Privacy Policy explains what information we collect when you use
            our website and services (the &ldquo;Platform&rdquo;), how we use and share that information,
            and the choices you have. By using the Platform, you agree to the practices described
            in this policy. This policy is incorporated by reference into our{' '}
            <Link href="/terms" className="text-orange-400 hover:text-orange-300">Terms of Service</Link>.
          </p>
        </div>

        <div className="space-y-10 text-zinc-300 leading-relaxed">

          {/* 1. Information We Collect */}
          <section>
            <h2 className="text-xl font-bold text-white mb-3">1. Information We Collect</h2>
            <p className="mb-4">
              We collect information you provide directly, information generated by your use of the
              Platform, and limited technical information from your device and browser.
            </p>

            <h3 className="text-base font-semibold text-white mb-2">1.1 Account and Profile Information</h3>
            <p className="mb-3">
              When you register and set up your profile, we collect:
            </p>
            <ul className="list-disc list-outside ml-5 space-y-2 mb-4">
              <li>
                <strong className="text-white">Identity information:</strong> First name, last name,
                username, and email address.
              </li>
              <li>
                <strong className="text-white">Location information:</strong> Zip code (used to
                display your general region to other riders and to suggest nearby connections).
                We do not collect precise GPS location.
              </li>
              <li>
                <strong className="text-white">Profile details:</strong> Relationship status, riding
                styles, a short bio, profile photo, and cover photo.
              </li>
              <li>
                <strong className="text-white">Garage / motorcycle information:</strong> Year, make,
                and model of motorcycles you add to your profile garage. This information is
                displayed publicly on your profile.
              </li>
            </ul>

            <h3 className="text-base font-semibold text-white mb-2">1.2 Content You Post</h3>
            <p className="mb-3">
              We collect and store content you create and share on the Platform, including:
            </p>
            <ul className="list-disc list-outside ml-5 space-y-2 mb-4">
              <li>Posts (text, photos, and combinations of both).</li>
              <li>Comments and replies on posts.</li>
              <li>Likes and reactions to posts and comments.</li>
              <li>Group memberships and content posted within groups.</li>
              <li>
                Wall posts and content posted on other users&rsquo; profiles.
              </li>
            </ul>

            <h3 className="text-base font-semibold text-white mb-2">1.3 Communications</h3>
            <p className="mb-4">
              When you use our direct messaging feature, the contents of those messages are stored
              on our servers. Messages are intended to be private between participants; however, they
              may be reviewed by our team in response to a valid report of abuse or a legal
              requirement.
            </p>

            <h3 className="text-base font-semibold text-white mb-2">1.4 Social Connections</h3>
            <p className="mb-4">
              We collect information about your social connections on the Platform, including friend
              requests sent and received, accepted friendships, users you have blocked, and reports
              you have submitted.
            </p>

            <h3 className="text-base font-semibold text-white mb-2">1.5 Usage Information</h3>
            <p className="mb-3">
              We automatically collect certain information when you use the Platform:
            </p>
            <ul className="list-disc list-outside ml-5 space-y-2 mb-4">
              <li>
                <strong className="text-white">Activity timestamps:</strong> When you last visited
                the Platform (used to show &ldquo;online recently&rdquo; indicators to other users).
              </li>
              <li>
                <strong className="text-white">Notification interactions:</strong> Whether you have
                read notifications, and when.
              </li>
              <li>
                <strong className="text-white">Content interactions:</strong> Posts you have liked
                or commented on.
              </li>
            </ul>

            <h3 className="text-base font-semibold text-white mb-2">1.6 Technical Information</h3>
            <p className="mb-3">
              Our infrastructure provider (Supabase) and hosting provider (Vercel) may automatically
              collect standard technical information when you access the Platform, including:
            </p>
            <ul className="list-disc list-outside ml-5 space-y-2">
              <li>IP address.</li>
              <li>Browser type and version.</li>
              <li>Operating system.</li>
              <li>Referring URLs.</li>
              <li>Date and time of access.</li>
            </ul>
            <p className="mt-3 text-sm text-zinc-400">
              This information is used for security monitoring, fraud prevention, and platform
              reliability. We do not use this data to build advertising profiles.
            </p>
          </section>

          {/* 2. How We Use Your Information */}
          <section>
            <h2 className="text-xl font-bold text-white mb-3">2. How We Use Your Information</h2>
            <p className="mb-3">We use the information we collect to:</p>
            <ul className="list-disc list-outside ml-5 space-y-2">
              <li>
                <strong className="text-white">Operate the Platform:</strong> Create and manage
                your account, display your profile and content to other users, and deliver the
                features and services you use.
              </li>
              <li>
                <strong className="text-white">Facilitate connections:</strong> Suggest nearby
                riders based on your zip code, enable friend requests and group participation,
                and power the people discovery features.
              </li>
              <li>
                <strong className="text-white">Send notifications:</strong> Deliver in-app and
                email notifications about activity relevant to your account (friend requests,
                messages, post interactions, group events, and legal notices such as DMCA
                takedown notices).
              </li>
              <li>
                <strong className="text-white">Moderate and maintain safety:</strong> Review
                reported content, enforce our Terms of Service and Community Guidelines, process
                DMCA takedown notices and counter-notices, and protect users from harassment,
                spam, and abuse.
              </li>
              <li>
                <strong className="text-white">Improve the Platform:</strong> Understand how the
                Platform is used in aggregate to diagnose technical issues and improve features.
              </li>
              <li>
                <strong className="text-white">Comply with legal obligations:</strong> Respond to
                lawful requests from government authorities, process copyright infringement
                notices, and meet our obligations under applicable law.
              </li>
            </ul>
          </section>

          {/* 3. How We Share Your Information */}
          <section>
            <h2 className="text-xl font-bold text-white mb-3">3. How We Share Your Information</h2>
            <p className="mb-4">
              We do not sell your personal information to third parties. We share your information
              only in the limited circumstances described below.
            </p>

            <h3 className="text-base font-semibold text-white mb-2">3.1 With Other Users</h3>
            <p className="mb-4">
              Much of the information you provide is shared with other registered users of the
              Platform as part of the social networking experience. This includes your profile
              information (name, username, zip code region, riding styles, profile and cover photo,
              garage), posts and photos you share, comments and likes, and your group memberships.
              Direct messages are shared only with the intended recipient.
            </p>

            <h3 className="text-base font-semibold text-white mb-2">3.2 Service Providers</h3>
            <p className="mb-4">
              We use trusted third-party service providers to help operate the Platform. These
              providers access your information only as necessary to perform services on our behalf
              and are contractually obligated to protect it:
            </p>
            <ul className="list-disc list-outside ml-5 space-y-2 mb-4">
              <li>
                <strong className="text-white">Supabase</strong> — database, user authentication,
                and file storage (images, photos). Your data is stored on Supabase&rsquo;s
                infrastructure, which is hosted on AWS in the United States.
              </li>
              <li>
                <strong className="text-white">Vercel</strong> — website hosting and content
                delivery. Vercel processes request data (including IP addresses) as part of
                delivering the Platform to you.
              </li>
              <li>
                <strong className="text-white">NHTSA (National Highway Traffic Safety
                Administration)</strong> — when you add a motorcycle to your garage, we query
                the NHTSA public API using the make and model year you provide. No personally
                identifiable information is sent to NHTSA.
              </li>
            </ul>

            <h3 className="text-base font-semibold text-white mb-2">3.3 DMCA Counter-Notice Forwarding</h3>
            <p className="mb-4">
              If you submit a DMCA counter-notice disputing a takedown of your content, we are
              legally required under 17 U.S.C. § 512(g)(3) to forward your counter-notice —
              including your name, address, and contact information — to the original complainant.
              By submitting a counter-notice, you consent to this forwarding.
            </p>

            <h3 className="text-base font-semibold text-white mb-2">3.4 Legal Requirements</h3>
            <p className="mb-4">
              We may disclose your information when we believe disclosure is necessary to comply
              with applicable law, respond to a valid legal process (such as a subpoena or court
              order), protect the rights, property, or safety of BikerOrNot, our users, or the
              public, or investigate and prevent fraud or security incidents.
            </p>

            <h3 className="text-base font-semibold text-white mb-2">3.5 Business Transfers</h3>
            <p>
              If BikerOrNot is involved in a merger, acquisition, financing, or sale of all or
              a portion of its assets, your information may be transferred as part of that
              transaction. We will notify you via email or a prominent notice on the Platform if
              your information becomes subject to a different privacy policy as a result.
            </p>
          </section>

          {/* 4. Information Visible on Your Profile */}
          <section>
            <h2 className="text-xl font-bold text-white mb-3">4. What Other Users Can See</h2>
            <p className="mb-3">
              The following information is visible to other registered users of the Platform:
            </p>
            <ul className="list-disc list-outside ml-5 space-y-2 mb-4">
              <li>Your first name, last name, and username.</li>
              <li>Your profile photo and cover photo.</li>
              <li>Your general location (city/state derived from your zip code).</li>
              <li>Your riding styles and bio.</li>
              <li>Your garage (motorcycles you have added to your profile).</li>
              <li>Your posts, photos, and comments (except those posted in private groups).</li>
              <li>Your friend count and mutual friend connections.</li>
            </ul>
            <p className="mb-3">
              The following information is <strong className="text-white">not</strong> visible to
              other users:
            </p>
            <ul className="list-disc list-outside ml-5 space-y-2">
              <li>Your email address.</li>
              <li>Your exact zip code or precise location.</li>
              <li>Your direct message conversations.</li>
              <li>Users you have blocked or reported.</li>
              <li>Your account password or authentication credentials.</li>
            </ul>
            <p className="mt-4 text-sm text-zinc-400">
              Content posted within private groups is visible only to active members of that group.
            </p>
          </section>

          {/* 5. Cookies and Tracking */}
          <section>
            <h2 className="text-xl font-bold text-white mb-3">5. Cookies and Similar Technologies</h2>
            <p className="mb-3">
              We use cookies and similar technologies to operate and secure the Platform. Specifically:
            </p>
            <ul className="list-disc list-outside ml-5 space-y-2 mb-4">
              <li>
                <strong className="text-white">Authentication cookies:</strong> Used to keep you
                signed in between sessions. These are set by Supabase and are essential to the
                Platform&rsquo;s operation.
              </li>
              <li>
                <strong className="text-white">Session cookies:</strong> Temporary cookies that
                expire when you close your browser, used to maintain your session state.
              </li>
            </ul>
            <p>
              We do not use third-party advertising cookies or tracking pixels. We do not use
              your browsing activity to serve you targeted advertisements.
            </p>
          </section>

          {/* 6. Data Retention */}
          <section>
            <h2 className="text-xl font-bold text-white mb-3">6. Data Retention</h2>
            <p className="mb-3">
              We retain your personal information for as long as your account is active or as
              needed to provide you with the Platform&rsquo;s services. Specifically:
            </p>
            <ul className="list-disc list-outside ml-5 space-y-2 mb-4">
              <li>
                <strong className="text-white">Active accounts:</strong> We retain all account
                and profile data while your account remains active.
              </li>
              <li>
                <strong className="text-white">Deleted accounts:</strong> When you delete your
                account, your profile is removed from public view. Some data (such as content
                you posted that other users interacted with, or records required for legal
                compliance) may be retained in anonymized or limited form for up to 90 days
                or as required by law.
              </li>
              <li>
                <strong className="text-white">DMCA records:</strong> DMCA notices, counter-notices,
                and related records are retained for a minimum of 3 years to fulfill our legal
                obligations under the DMCA.
              </li>
              <li>
                <strong className="text-white">Legal holds:</strong> If your account is involved
                in an active legal proceeding, we may retain relevant data until the matter is
                resolved.
              </li>
            </ul>
            <p>
              Uploaded images and files may remain on our storage infrastructure for a brief
              period after deletion while propagating through our content delivery network.
            </p>
          </section>

          {/* 7. Your Rights and Choices */}
          <section>
            <h2 className="text-xl font-bold text-white mb-3">7. Your Rights and Choices</h2>

            <h3 className="text-base font-semibold text-white mb-2">7.1 Access and Correction</h3>
            <p className="mb-4">
              You can access and update most of your account information at any time through your
              account settings, including your name, username, profile photo, bio, zip code,
              relationship status, riding styles, and garage.
            </p>

            <h3 className="text-base font-semibold text-white mb-2">7.2 Account Deletion</h3>
            <p className="mb-4">
              You may delete your account at any time through your account settings. Upon deletion,
              your profile will be removed from public view. Please refer to Section 6 for
              information on what data may be retained after deletion.
            </p>

            <h3 className="text-base font-semibold text-white mb-2">7.3 Notification Preferences</h3>
            <p className="mb-4">
              You can manage your in-app notification preferences from your account settings.
              Certain operational and legal notices (such as DMCA takedown notifications) cannot
              be disabled while your account is active, as they are required communications.
            </p>

            <h3 className="text-base font-semibold text-white mb-2">7.4 Content Removal</h3>
            <p className="mb-4">
              You may delete your own posts, photos, and comments at any time. Deleted content
              is removed from public view immediately. If your content was removed due to a DMCA
              takedown and you believe the removal was in error, you have the right to submit a{' '}
              <Link href="/dmca/counter-notice" className="text-orange-400 hover:text-orange-300">
                counter-notice
              </Link>
              .
            </p>

            <h3 className="text-base font-semibold text-white mb-2">7.5 Data Requests</h3>
            <p>
              To request a copy of the personal information we hold about you, or to request
              deletion of your data beyond what is available through your account settings,
              please contact us at{' '}
              <a href="mailto:legal@bikerornot.com" className="text-orange-400 hover:text-orange-300">
                legal@bikerornot.com
              </a>
              . We will respond to verifiable requests within 30 days.
            </p>
          </section>

          {/* 8. California Privacy Rights */}
          <section>
            <h2 className="text-xl font-bold text-white mb-3">8. California Privacy Rights (CCPA)</h2>
            <p className="mb-3">
              If you are a California resident, you have specific rights under the California
              Consumer Privacy Act (&ldquo;CCPA&rdquo;) and the California Privacy Rights Act (&ldquo;CPRA&rdquo;),
              including:
            </p>
            <ul className="list-disc list-outside ml-5 space-y-2 mb-4">
              <li>
                <strong className="text-white">Right to Know:</strong> You have the right to
                request that we disclose the categories and specific pieces of personal information
                we have collected about you.
              </li>
              <li>
                <strong className="text-white">Right to Delete:</strong> You have the right to
                request deletion of personal information we have collected, subject to certain
                exceptions.
              </li>
              <li>
                <strong className="text-white">Right to Correct:</strong> You have the right to
                request correction of inaccurate personal information.
              </li>
              <li>
                <strong className="text-white">Right to Opt Out of Sale or Sharing:</strong> We
                do not sell or share your personal information with third parties for advertising
                purposes. No opt-out is required, but you may contact us to confirm.
              </li>
              <li>
                <strong className="text-white">Right to Non-Discrimination:</strong> We will not
                discriminate against you for exercising any of your CCPA rights.
              </li>
            </ul>
            <p>
              To exercise your California privacy rights, please contact us at{' '}
              <a href="mailto:legal@bikerornot.com" className="text-orange-400 hover:text-orange-300">
                legal@bikerornot.com
              </a>
              . We will verify your identity before processing your request.
            </p>
          </section>

          {/* 9. Data Security */}
          <section>
            <h2 className="text-xl font-bold text-white mb-3">9. Data Security</h2>
            <p className="mb-3">
              We take reasonable technical and organizational measures to protect your personal
              information against unauthorized access, alteration, disclosure, or destruction.
              These measures include:
            </p>
            <ul className="list-disc list-outside ml-5 space-y-2 mb-4">
              <li>Encrypted transmission of data over HTTPS/TLS.</li>
              <li>
                Row-Level Security (RLS) policies on our database to ensure users can only
                access data they are authorized to see.
              </li>
              <li>
                Separation of service-level (administrative) credentials from user-facing
                authentication.
              </li>
              <li>
                Passwords are never stored in plaintext — authentication is handled by Supabase
                Auth using industry-standard hashing.
              </li>
            </ul>
            <p>
              No method of transmission over the internet or electronic storage is 100% secure.
              While we strive to protect your personal information, we cannot guarantee its
              absolute security. If you believe your account has been compromised, please contact
              us immediately at{' '}
              <a href="mailto:support@bikerornot.com" className="text-orange-400 hover:text-orange-300">
                support@bikerornot.com
              </a>.
            </p>
          </section>

          {/* 10. Children's Privacy */}
          <section>
            <h2 className="text-xl font-bold text-white mb-3">10. Children&rsquo;s Privacy</h2>
            <p>
              BikerOrNot is intended solely for users 18 years of age and older. We do not
              knowingly collect, solicit, or maintain personal information from anyone under 18.
              If we learn that we have inadvertently collected personal information from a person
              under 18, we will delete that information and terminate the associated account
              promptly. If you believe we may have information from or about a minor, please
              contact us at{' '}
              <a href="mailto:legal@bikerornot.com" className="text-orange-400 hover:text-orange-300">
                legal@bikerornot.com
              </a>.
            </p>
          </section>

          {/* 11. Third-Party Services */}
          <section>
            <h2 className="text-xl font-bold text-white mb-3">11. Third-Party Services and Links</h2>
            <p className="mb-3">
              The Platform may contain links to third-party websites or services not operated by
              BikerOrNot. We are not responsible for the privacy practices of those third parties.
              We encourage you to review their privacy policies before providing any personal
              information.
            </p>
            <p>
              Our use of third-party infrastructure services (Supabase, Vercel) means your data
              may be processed and stored on systems subject to those providers&rsquo; privacy and
              security policies. We have selected providers that offer strong data protection
              commitments consistent with our obligations to you.
            </p>
          </section>

          {/* 12. International Users */}
          <section>
            <h2 className="text-xl font-bold text-white mb-3">12. International Users</h2>
            <p>
              BikerOrNot is operated from the United States, and our infrastructure is hosted in
              the United States. If you access the Platform from outside the United States, please
              be aware that your information will be transferred to, stored, and processed in the
              United States, where data protection laws may differ from those in your country.
              By using the Platform, you consent to the transfer of your information to the
              United States.
            </p>
          </section>

          {/* 13. Changes */}
          <section>
            <h2 className="text-xl font-bold text-white mb-3">13. Changes to This Policy</h2>
            <p className="mb-3">
              We may update this Privacy Policy from time to time. When we make material changes,
              we will notify you by updating the &ldquo;Effective Date&rdquo; at the top of this page and,
              where appropriate, by sending an email to the address associated with your account
              or displaying a prominent notice on the Platform.
            </p>
            <p>
              Your continued use of the Platform after any changes to this Privacy Policy
              constitutes your acceptance of the updated policy. We encourage you to review this
              policy periodically.
            </p>
          </section>

          {/* 14. Contact */}
          <section>
            <h2 className="text-xl font-bold text-white mb-3">14. Contact Us</h2>
            <p className="mb-4">
              If you have questions, concerns, or requests regarding this Privacy Policy or how
              we handle your personal information, please contact us:
            </p>
            <div className="bg-zinc-900 border border-zinc-800 rounded-xl p-5 text-sm space-y-1.5">
              <p className="text-white font-semibold">BikerOrNot.com — Privacy</p>
              <p>
                Email:{' '}
                <a href="mailto:legal@bikerornot.com" className="text-orange-400 hover:text-orange-300">
                  legal@bikerornot.com
                </a>
              </p>
              <p>
                Support:{' '}
                <a href="mailto:support@bikerornot.com" className="text-orange-400 hover:text-orange-300">
                  support@bikerornot.com
                </a>
              </p>
              <p>
                Website:{' '}
                <a href="https://www.bikerornot.com" className="text-orange-400 hover:text-orange-300">
                  www.bikerornot.com
                </a>
              </p>
            </div>
            <p className="mt-4 text-sm text-zinc-400">
              We will respond to all verifiable privacy requests within 30 days. For security
              purposes, we may need to verify your identity before processing certain requests.
            </p>
          </section>

        </div>
      </div>

      <footer className="border-t border-zinc-800 py-8 px-6 mt-16">
        <div className="max-w-3xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-3 text-sm text-zinc-600">
          <p>&copy; {new Date().getFullYear()} BikerOrNot.com. All rights reserved.</p>
          <div className="flex items-center gap-4">
            <Link href="/privacy" className="hover:text-zinc-400 transition-colors">Privacy Policy</Link>
            <Link href="/dmca" className="hover:text-zinc-400 transition-colors">DMCA Policy</Link>
            <Link href="/terms" className="hover:text-zinc-400 transition-colors">Terms of Service</Link>
          </div>
        </div>
      </footer>
    </div>
  )
}
